[package]
name = "paramdex-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.15.0"
thiserror = "1.0.37"
pest = "2.4.0"
pest_derive = "2.4.0"

[dev-dependencies]
walkdir = "2.3.2"
